# Generated by Django 5.2.8 on 2025-11-29 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0002_remove_order_customer_remove_order_supplier_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='quantity_available',
            new_name='quantity',
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory_app.supplier'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='inventory_app.product'),
        ),
    ]
